-- AlterTable
ALTER TABLE `user_store_review` ADD COLUMN `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `imageUrl` VARCHAR(255) NULL,
    ADD COLUMN `star` TINYINT NULL;
